### ISSUE TITLE
Cursor pointer

### ISSUE THREAD

**Issue by brainmaniac** [pipe-dream/laravel#1]
Thanks for impressive work. 👏 This will surely greatly speed up mocking new projects!! 👍 

Cursor pointer when hovering the nav tabs would increase userfriendlieness a lot! 👆 

https://tailwindcss.com/docs/cursor/#pointer

Tried to make PR but failed due to:
`fatal: Authentication failed for 'https://brainmaniac@github.com/pipe-dream/laravel.git/'`

... maybe my fault I don't know but to tired to investigate but thought I'd leave it here if someone else reports the same issue.

Again, impressive and congratulations to the release!!! 🎉

**Comment by ajthinking** [comment]
Thx brain, I implemented the cursor, great idea!
Im assuming somethings up with the two factor auth and your account, so gonna close this for now.
#CloseEmLikeTayTay

**Comment by ajthinking** [comment]
@brainmaniac FYI det funkade med ett annat account
