### ISSUE TITLE
Add folding(collapsing) feature for the schema tab

### ISSUE THREAD

**Issue by PeterKravets** [pipe-dream/laravel#16]
It would be great to add fold for the schema tab especially in case of a lot of data.
Like on the main example of ace editor
https://ace.c9.io/

**Comment by ajthinking** [comment]
Thanks @PeterKravets good idea!

![image](https://user-images.githubusercontent.com/3457668/59277242-22329480-8c60-11e9-8f0f-b9fe8d8b442b.png)
