### ISSUE TITLE
Save the sketch to localstorage

### ISSUE THREAD

**Issue by elbojoloco** [pipe-dream/laravel#22]
Hi!

So far loving this package. Although I have not been able to use it without some anxiety of accidentally refreshing/closing the page! All contents of my sketch will dissapear and I will have to start over (yes, i could copy it over to a backup file constantly, but that isn't very nice now is it). So here's the simple suggestion: automatically store the sketch in localstorage so that we don't have to fear refreshing the page.

**Comment by ajthinking** [comment]
Thanks for the suggestion @elbojoloco, this is a must have. Would like that save process to cover ALL inputs in the UI, not just the sketch. That makes it slightly more complex to fix. Putting it on the [todo trello board](https://trello.com/b/R11mhfdy/pipe-dream) for now.

Also more info here: https://github.com/pipe-dream/laravel/pull/25 (thanks @sinaghazi)

**Comment by ajthinking** [comment]
Thanks @elbojoloco ! This is queued in next version, closing for now.
