### ISSUE TITLE
How to implement 'enum' datatype with default value in 'Object Model' ?

### ISSUE THREAD

**Issue by more-yogesh** [pipe-dream/laravel#28]
Trying to add enum datatype for 'gender' field that requires values 'male' and 'female' which can easily be achieved by 'enum' data type but it's not mentioned in 'object model' as well as in templates. the default value will be appreciated :) 

One more thing it's not working in windows 7. Here are some screenshots 

![build](https://user-images.githubusercontent.com/24932160/59323955-8efa6d00-8cfa-11e9-9ecc-bdc2985ab80b.PNG)
![console](https://user-images.githubusercontent.com/24932160/59323957-8f930380-8cfa-11e9-9f19-770e7cb6b16d.PNG)
![review](https://user-images.githubusercontent.com/24932160/59323958-8f930380-8cfa-11e9-8d31-905fd3ed21aa.PNG)
![settings](https://user-images.githubusercontent.com/24932160/59323959-8f930380-8cfa-11e9-85f9-fbbabd8e1177.PNG)

Thanks for the unique package :+1:

**Comment by ajthinking** [comment]
Thanks for the report @more-yogesh !

### regarding enum
`enum` is currently not implemented. (I did fixed the ~20 most common values but must have missed enum). Here is the full list of what is left to fix: https://trello.com/c/wPZupMVh for anyone who wants do dig in.

### regarding bug windows 7
Can you provide
* pipe-dream/laravel version (if not the latest you might want to test a fresh install v0.0.44)
* laravel version
* does it crash on start? If not what actions leads to the crash?

**Comment by ajthinking** [comment]
Just adding a note here. Currently the system cant handle datatypes with more than one parameter. That is the case for enum:
`$table->enum('level', ['easy', 'hard']);`
numbers with precision and scale:
`$table->double('amount', 8, 2);`
and length parameters:
`$table->char('name', 100);`

That might take a while to fix.

**Comment by more-yogesh** [comment]
> Thanks for the report @more-yogesh !
> 
> ### regarding enum
> `enum` is currently not implemented. (I did fixed the ~20 most common values but must have missed enum). Here is the full list of what is left to fix: https://trello.com/c/wPZupMVh for anyone who wants do dig in.
> 
> ### regarding bug windows 7
> Can you provide
> 
> * pipe-dream/laravel version (if not the latest you might want to test a fresh install v0.0.44)
> * laravel version
> * does it crash on start? If not what actions leads to the crash?

Laravel(5.8) and pipe-dreams(0.44) both are in the latest version same issue is occurring, No crashing at all just not working as needed.

**Comment by ajthinking** [comment]
Thanks for the update. Looking closer at your screenshots I saw you are running Laravel out of the public dir, thats not gonna work because pipedream need to fecth stuff out of the root.
![image](https://user-images.githubusercontent.com/3457668/59419179-a739bd00-8dca-11e9-8ddb-7b024286b18f.png)

Did you look into using homestead? Its a bit of a pain to setup, but its worth it.

**Comment by more-yogesh** [comment]
:1st_place_medal:  for running this in the window 7 OS we need to use `php artisan serve` now it's working like a charm, Thanks AJ for your closer analysis.

**Comment by ajthinking** [comment]
Happy to hear its working 👍
