### ISSUE TITLE
Use Laravel Resources Collection along with pagination for API controllers

### ISSUE THREAD

**Issue by KluVerKamp** [pipe-dream/laravel#32]
Since this great tool aim to use the best practices in industry, it would be super awesome to have pagination along with resources collection for each API controllers rather than something like `all()`

**Comment by aligajani** [comment]
Good idea but I think this is a new package, so there's a lot to add.

**Comment by ajthinking** [comment]
Great idea @KluVerKamp, thanks! Will add this to the [trello board](https://trello.com/b/R11mhfdy/pipe-dream). 

Haha true that @aligajani :)

**Comment by ajthinking** [comment]
Fixed by @Vestibule in #39 🚀

**Comment by KluVerKamp** [comment]
@aligajani of course, we just keep track for anything for the author here, shame I have been so busy lately otherwise I would do that myself.
Glad that @Vestibule made a great job there!
