### ISSUE TITLE
Getting " No files yet!" in the review tab after writing the sketch

### ISSUE THREAD

**Issue by albalooshi** [pipe-dream/laravel#34]
After writing any sketch ( or even using the sample one), I cans see that the json schema getting updated. However when I ever visit the "Review" or "Build" tab I get an empty page with "No files yet!"

MacOS Mojave 10.14.5 
Laravel 5.8 (clean install)
PipeDream 0.0.45

Thank you!

**Comment by ajthinking** [comment]
Hi @albalooshi, thanks I merged this one PR to quickly :)
releasing v0.0.46 in a sec

**Comment by Muhammadinaam** [comment]
Hi, I just installed it today (23-June-2019) and I am getting same issue. "No files yet!" in review tab and "No files to build yet" in Build tab. 

Windows 10
Laravel 5.8 (clean install)
PipeDream 0.0.46
