### ISSUE TITLE
SÅ FANTASTISKT BRA!!!!

### ISSUE THREAD

**Issue by tanthammar** [pipe-dream/laravel#35]
Anders :) stort TACK för att du gjort pipe-dream - så j****vla bra!

**Comment by ajthinking** [comment]
Oooooh! TACK, va kul att se att sverige hittat hit! Gjorde min dag :)

**Comment by ajthinking** [comment]
@tanthammar ! Kolla posten i Laravel Sverige :)

**Comment by tanthammar** [comment]
Jag är gärna med o hjälper till. Skulle vilja ge mig på resource collections, api controllers, o form requests med support för mpociot/laravel-apidoc-generator. Därefter hade jag velat implementera views/controllers baserat inertiajs.

**Comment by ajthinking** [comment]
Grymt @tanthammar 🚀🎉😄
