### ISSUE TITLE
Love the idea. It would be great if you add views template.

### ISSUE THREAD

**Issue by mohapinkepane** [pipe-dream/laravel#37]
It would be niece if you included view templates.

**Comment by vesper8** [comment]
agreed, it would be amazing if this could generated a full Vue-based CRUD, ideally standalone that connects via API. This may be out of scope though.. but it's only a matter of time before a user adds all the stubs necessary to do that

**Comment by ajthinking** [comment]
Thanks guys for this idea!
I think we will go with a separate `VueFileFactory` in next version. A user will then be able to deploy multiple FileFactories to create the desired stack. 

Until then PR:s are welcome on this repo. The easiest way would be to add a new `VuePipe` to the `LaravelFileFactory`

**Comment by phikhi** [comment]
Or maybe instead of generating a vue-based CRUD, we could generate Nova resources instead... or do both 😄

**Comment by ajthinking** [comment]
Thanks @mohapinkepane, @vesper8  and @phikhi! This is queued for next version, closing for now.
