### ISSUE TITLE
Let us manually change the order of migrations

### ISSUE THREAD

**Issue by septIO** [pipe-dream/laravel#38]
Currently the order is automatically chosen to make sure that reference tables are made before the reference is declared on another table. This doesn't always work.

Can we make it so that we can manually change the order in the Preview area?

**Comment by ajthinking** [comment]
Thanks for the report @septIO !
Can you supply an example sketch where the sorting does not work?
I think there are cases where the table structure requires an ALTER TABLE statement add foreign keys.

**Comment by septIO** [comment]
I'm currently working on a pull request that implements a better sorting algorithm.
That should take care of the problem.
