### ISSUE TITLE
"No files yet!" in review tab

### ISSUE THREAD

**Issue by Muhammadinaam** [pipe-dream/laravel#41]
I am getting same issue (closed) https://github.com/pipe-dream/laravel/issues/34

Hi, I just installed it today (23-June-2019) and I am getting issue "No files yet!" in review tab and "No files to build yet" in Build tab.

Windows 10
Laravel 5.8 (clean install)
PipeDream 0.0.46

**Note:**
When I run php artisan serve, and use url http://localhost:8000/pipe-dream then it works fine. But when I open without php artisan serve and use url http://localhost/myproject/public/pipe-dream then this I faced this issue.

Thanks

**Comment by ajthinking** [comment]
Thanks for reporting @Muhammadinaam! 
I think running it with `serve` like you mention or using a homestead setup is the way you need to go on windows since the api does need a proper root.
See also [#28](https://github.com/pipe-dream/laravel/issues/28) (the windows part).
