### ISSUE TITLE
Big projects will almost kill the browser

### ISSUE THREAD

**Issue by septIO** [pipe-dream/laravel#46]
When writing big projects (20+ models) pipe-dream starts to be incredibly slow - we're talking multiple seconds of waiting timer per keystroke.

**Comment by ajthinking** [comment]
Thanks @septIO this is noted in [trello](https://trello.com/b/R11mhfdy/pipe-dream). Maybe you saw the implementation in `ObjectModelEntity` and `ObjectModelEntityFactory` its really hairy, and most likely need a total rewrite.

**Comment by septIO** [comment]
@ajthinking I'll take a look at optimizing that later

**Comment by ajthinking** [comment]
Thanks @septIO septIO for this and all your other contributions! Id love if we can make those kind of big improvements to the next version.

Check out this overview: https://github.com/pipe-dream/docs
Im trying to first recreate the current functionality in those repos, and then refactor.

**Comment by septIO** [comment]
Sure, I'll work on functionality instead then :)

**Comment by ajthinking** [comment]
Thanks @septIO 🚀🚀🚀 Didn't mean to impede, just want to make sure we can transfer and integrate all your features/fixes to the other repo as soon as the initial scaffolding is ready
