### ISSUE TITLE
Help button wipes work on sketch

### ISSUE THREAD

**Issue by ordago** [pipe-dream/laravel#49]
steps:
1 write something in the sketch and then click help button. It replaces the content of the sketch without warning.

* OS, browser: Windows 10, Chrome
* pipe-dream version: ^0.0.71

**Comment by ajthinking** [comment]
Thanks @ordago, this is really treacherous behavior. Its listed in the [trello todo](https://trello.com/b/R11mhfdy/pipe-dream). Next version will have a fix but that might take a while.

**Comment by ajthinking** [comment]
Thanks @ordago! This is queued for next version, closing for now.
