### ISSUE TITLE
Carriage Return in names

### ISSUE THREAD

**Issue by ordago** [pipe-dream/laravel#50]
"User\r"

I copied the sketch in notepad++ as to not to lose my work. When I copied it abck in the sketch window it had the carriage return character `r` in all the names.

![chrome_gNoUSK8xfw](https://user-images.githubusercontent.com/6376814/60388749-c19fb600-9aad-11e9-80cf-28469fda30ee.png)

* OS, browser: W10, Chrome
* pipe-dream version: ^0.0.71

**Comment by ajthinking** [comment]
Thanks for reporting @ordago! This is fixed in `v0.0.72` by #51
