### ISSUE TITLE
Configure model folder

### ISSUE THREAD

**Issue by cloudstudio** [pipe-dream/laravel#52]
Hey ! nice work man! I love it, I make this package for laravel nova : https://github.com/cloudstudio/resource-generator and as we did here could be nice, configure some settings, like model folder, sometimes users use \App\Models\Model folder, what you think?

Cheers!

**Comment by ajthinking** [comment]
Hey @cloudstudio ! Beautiful package you got going! Thats a great inspiration.
Theres a plan for configuration like that to be exposed under settings, something like:

![image](https://user-images.githubusercontent.com/3457668/60422782-0847fa00-9bed-11e9-8c18-fea0b36ddc26.png)

And Thank you for the kind words :)

**Comment by cloudstudio** [comment]
@ajthinking yeah! something like this I say, perfect !
