### ISSUE TITLE
belongsToMany vs hasMany

### ISSUE THREAD

**Issue by septIO** [pipe-dream/laravel#55]
At the moment these doesn't always get it right,
i suggest a scheme where the first word is the "owner", and the second is the "child"

Example:
`cart_product`

```
Cart HasMany Products
Product BelongsTo Cart
```

**Comment by ajthinking** [comment]
Not sure I understand 100%. Can you provide another example ?

The [convention](https://laravel.com/docs/5.8/eloquent-relationships#many-to-many) when setting up a many to many table is to use the alphabetical order of the related model names joined by a `_`.

I do agree it is not easy and not obvious.

Do you see any other way of doing that maybe using the proposed sketch line args?

```
Cart : hasMany Product
payed

Product : hasMany Cart
name
```

???

 Thanks !!

**Comment by septIO** [comment]
If we're gonna go with the line args, then i purpose this solution instead:
```
Car
garage_id : hasMany
user_id : belongsTo
```

The alphabetization is only for Laravel to actually guess the table name. Else it wouldn't know whether to look in `product_cart`  or `cart_product`. It's not a convention. It works fine when people are manually making the relationships inside their models, but we're trying to automate it, so we'll have to go a little out of conventional ways of doing things.

We can still alphabetize the table name, just that when the sketch determines the relationship ´the order will matter.

```
garage_car -> Garage hasMany Car - Car belongsTo Garage
car_garage -> Car hasMany Garage - Garage belongsTo 
```
The tablename will be `car_garage` for both of the above pivot tables.

**Comment by robtesch** [comment]
> The alphabetization is only for Laravel to actually guess the table name. Else it wouldn't know whether to look in `product_cart` or `cart_product`. It's not a convention. It works fine when people are manually making the relationships inside their models, but we're trying to automate it, so we'll have to go a little out of conventional ways of doing things.
> 
> We can still alphabetize the table name, just that when the sketch determines the relationship ´the order will matter.
> 
> ```
> garage_car -> Garage hasMany Car - Car belongsTo Garage
> car_garage -> Car hasMany Garage - Garage belongsTo Car
> ```
> 
> The tablename will be `car_garage` for both of the above pivot tables.

@septIO You don't use a pivot table for hasMany and belongsTo... you use a foreign_key on the "owned" model:

example:

'''
Garage
name
description

Car
garage_id
name
description
'''

**Comment by septIO** [comment]
@robtesch ManyToMany relationships need a pivot though. 

The examples here might not be the best, but it still doesn't change the fact that the auto-relationship doesn't work optimally.

ex:
```
User
name
email

Invoice
user_id
currency_id
address
country_id
status

InvoiceDetails
invoice_id
product_id
amount
price

Currency
name
iso

Country
name
currency_id

Product
name
catalog_id

Catalog
user_id
```

Now, this is a little more complicated collection. 
```
Invoice relations:
    User hasMany Invoices
    Invoice hasMany InvoiceDetails -> InvoiceDetails belongsTo Invoice
    Invoice hasOne Currency -> Currency belongsToMany Invoice
    Invoice hasOne Country -> Country belongsToMany Country

InvoiceDetail relations:
    InvoiceDetails hasOne Product -> Product belongsToMany InvoiceDetails

Country relations:
    Country hasOne Currency -> Currency belongsToMany Country

Product relations:
    Product belongsTo Catalog -> Catalog hasMany Products

Catalog relations:
    Catalog hasOne User -> User hasMany Catalog
```

If i open up open Postman and ask for `localhost/api/users/1` i would see that users invoices, each invoices details, each details products etc. However, this doesn't work. 

I've uploaded my current test sketch to pastebin here: [https://pastebin.com/QAAA15aC](https://pastebin.com/QAAA15aC)

**Comment by robtesch** [comment]
@septIO in your example relationships there are not ManyToMany relationships?

I think the way you could get this is by going:

```
return response()->json($user->load(['invoices.invoiceDetails.product', 'invoices.currency', 'invoices.country']));
```

Or something like that. Seems like there's quite a lot of circular relationships there.

**Comment by septIO** [comment]
Closed due to my complete misunderstanding of many-many relationships :)
Thank you @robtesch for letting me know :)

**Comment by robtesch** [comment]
@septIO happens to the best of us!
