### ISSUE TITLE
Make each model's "child files" foldable

### ISSUE THREAD

**Issue by septIO** [pipe-dream/laravel#57]
At the moment each "model" have tons of files:
controller
APIcontroller
resource
resourceCollection
migration
seed
factory
model

I suggest that all of these should be "collapseable" into their own group.

So a model named "Car" would have all of their files under that name. Look at just the sample app there are 28 files to look through, if we grouped them up, it would be so much easier to navigate through.

**Comment by ajthinking** [comment]
This would be a great enhancement! Adding it on Trello!

**Comment by ajthinking** [comment]
Thanks @septIO! Cleaning up a bit here, closing it for now.
