### ISSUE TITLE
I didn't get the meaning of reverseHistory

### ISSUE THREAD

**Issue by smartymoon** [pipe-dream/laravel#61]
Hi, this is an awesome project. After refresh brower and build a new model, I found I had lost all my previous models. It's for the reason of reverseHistory. and I can't disable it. 

so would it be better to remove this feature? I didn't get the meaning of reverseHistory.

Kind regards from china

**Comment by ajthinking** [comment]
Thanks XinBa for the kind words and for filing this issue.
The not persisting sketch/schema is an issue we need to resolve. The reasoning behind reverseHistory is to allow mistakes to be fixed on the fly and to avoid timestamp conflicts in migrations. It would be nice to be able to build in incremental steps also though.

Closing this for now as it is planned for the next version. Feel free to add any thoughts/ideas.

**Comment by smartymoon** [comment]
Thanks for your reply, I‘ am very happy about receiveing your message. It's my first time to talk with a foreigner and as you can see , I am not good at english.  :grin:

Persisting sketch/schema may be not necessary for me. pipe-dream helps me buiding an application on the fly, But I don't count on it doing everything for me，I will make a lot change on the files that pipe-dream generated.  I dont want pipe-dream to care about those files and regenerated it again.  If I make a mistake I will use git to recover the files.

When buiding an application, I can't design tables and models perfectly, changes always be there from begin to end. Maybe three month later, my boss told me, "I want manage cars", at that time I would like to open pipe-dream and config a model `Car` and I don't care the previous models I had made before

If I have said something rude, please forgive me , I really like pipe-dream and I am reading it's code :blush:

**Comment by ajthinking** [comment]
Thanks, I think I understand your use case better now: We need to make sure the users changes in their IDE is not overwritten by accident. 

Haha no - you have very good english and certainly not rude and Im happy you are using pipe dream 
 and reading the code😄If you want to know more here is some of the future plans: https://trello.com/b/R11mhfdy/pipe-dream
https://github.com/pipe-dream/docs
