### ISSUE TITLE
Create One to One relationship

### ISSUE THREAD

**Issue by kocuubirasap** [pipe-dream/laravel#8]
How to create one to one relationship on sketch, like many to many relationship use snake_case

**Comment by ajthinking** [comment]
Hi @kocuubirasap!  I just pushed something to get started with One To One relationships `v0.0.37`. Though it still requires you to go to the _schema_ and manually change the relationship arrays (HasMany to HasOne). 

## Example:

### sketch
```
User
name

Profile
user_id
```

### schema
```
    "User": {

        ...

        "relationships": {
            "hasOne": [
                "Profile"
            ],
            "hasMany": [],
            "belongsTo": [],
            "belongsToMany": []
        }
```

Any idea on a syntax to make that more smooth (directly in the sketch)? I would be happy to add that.

**Comment by kocuubirasap** [comment]
Ok thanks @ajthinking
